[package]
name = "auth"
version = "0.1.0"
edition = "2024"

[dependencies]
axum = "0.8.4"
dotenv = "0.15.0"
jsonwebtoken = "9.3.1"
serde = "1.0.219"
tokio = { version = "1.47.0", features = ["macros", "rt-multi-thread"] }
